---

services:
  pushgateway:
    container_name: $PUSHGATEWAY_NAME
    image: $PUSHGATEWAY_IMAGE
    ports:
      - $PUSHGATEWAY_PORT:9091
    volumes:
      - ./config/web-config.yaml:/etc/prometheus/web-config.yaml:ro
    command:
      - "--web.config.file=/etc/prometheus/web-config.yaml"
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
      resources:
        limits:
          memory: 512M
    networks:
      network:
        ipv4_address: $PUSHGATEWAY_HOST


networks:
  network:
    driver: bridge
    name: $PUSHGATEWAY_NETWORK
    ipam:
      config:
        - subnet: $PUSHGATEWAY_ADDRES
          gateway: $PUSHGATEWAY_GATEWAY
